#!/usr/bin/env bash
#insatlling nginx on the server
sudo apt-get -y install nginx
sudo ufw allow 80
sudo chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.html
sudo systemctl restart nginx
