#!/usr/bin/env bash
# 404 error
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chown -R "$USER":"$USER" /etc/nginx/*
sudo chmod -R 755 /etc/nginx/sites-available/default
sudo touch /var/www/html/custom_404.html
sudo chmod 777 /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo chmod 777 /var/www/html/*
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf %s "server {
        listen 80 default_server;
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}
        }" > /etc/nginx/sites-available/default
sudo service nginx restart
