#!/usr/bin/env bash
# 404 error
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chmod a+w /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo touch /usr/share/nginx/html/custom_404.html
sudo chmod a+w /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page\n" > /usr/share/nginx/html/custom_404.html
sudo chmod a+w /etc/nginx/sites-available/default
printf %s "server {
        listen 80 default_server;
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}
        }" > /etc/nginx/sites-available/default
sudo service nginx restart
