#!/usr/bin/env bash
# making a custom http header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chmod a+w /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx/sites-available/default
echo "server {                                                                  
    listen 80;                                                                  
    listen [::]:80 default_server;                                              
    root   /var/www//html;                                                      
    index index.nginx-debian.html index.nginx-debian.html;
    add_header X-Served-By $HOSTNAME;                    
                                                                     
}" > /etc/nginx/sites-available/default
sudo service nginx restart
