#!/usr/bin/env bash
#advanced task
sudo 
f="/var/run/holbertonscript.pid"
trap "echo To infinity and beyond" SIGTERM
trap "echo Y U no love me?!" SIGINT
echo $$ > $f
while true
do
echo To infinity and beyond
sleep 2
done
trap "sudo rm $f" SIGQUIT
