#!/usr/bin/env bash
#advanced task
file=/var/run/my_process.pid
case "$1" in
	start)
		./manage_my_process start &
		echo "$!" > $file
		echo "manage_my_process started"
		;;
	stop)
		pkill -f manage_my_process &
		rm $file &
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -f manage_my_process &
		rm $file
		./manage_my_process &
		echo "$!" > $file
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
