#!/usr/bin/env bash
#gives infromation about a file
file=holbertonschool
if test -e "$file";
then
	echo $file file exists
	if test ! -s "$file";
	then 
		echo $file file is empty
	else
		echo $file file is not empty
	fi
	if test -f "$file"
	then
		echo $file is a regular file
	fi
else
	echo $file file does not exist
fi
