#!/usr/bin/env bash
#configures a server with some requirments
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
