#!/usr/bin/env bash
#configures a server with some requirments
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed 's/157.240.11.35/8.8.8.8/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
